language: rust
cache:
    cargo: true
    directories:
        - 3proxy
rust:
    - stable
    - beta
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - rust: nightly

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc
            - libssl-dev

script:
    - curl -v -L https://codeload.github.com/z3APA3A/3proxy/legacy.tar.gz/devel -o 3proxy.tar.gz
    - tar -xvzf 3proxy.tar.gz -C 3proxy
    - cd 3proxy/z3APA3A-3proxy*
    - make -f Makefile.Linux
    - cd bin
    - |
        echo "
        internal 127.0.0.1
        users hyper:CL:proxy
        auth none strong
        socks
        " > 3proxy.cfg
    - ./3proxy 3proxy.cfg &
    - cd $TRAVIS_BUILD_DIR
    - cargo build -v --all

before_cache: |
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]
    then
        RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
        cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
    else
        cargo test -v --all
    fi
