language: rust
cache: cargo
rust:
    - stable
    - beta
    - nightly

matrix:
    allow_failures:
        -   rust: nightly

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc

script:
    - git clone https://github.com/z3APA3A/3proxy
    - cd 3proxy
    - make -f Makefile.Linux -j4
    - cd bin
    - |
        echo "
        internal 127.0.0.1
        users hyper:CL:proxy
        auth none strong
        socks
        " > 3proxy.cfg
    - ./3proxy 3proxy.cfg &
    - cd ../..
    - cargo build -v --all
    - cargo test -v --all
